language: java

before_install:
  - chmod +x gradlew
before_script:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
  - stage: jdk.java.net - OpenJDK - GPL
    env: JDK=8
    script: 
    - jdk_switcher use openjdk8
    - ./gradlew test
    - ./gradlew jacocoTestReport
  - # stage: ...
    env: JDK=9
    script: 
    - source install-jdk.sh -C -F 9
    - ./gradlew test
    - ./gradlew jacocoTestReport
  - # stage: ...
    env: JDK=10
    script: 
    - source install-jdk.sh -C -F 10
    - ./gradlew test
    - ./gradlew jacocoTestReport
     
  - stage: adoptopenjdk.net - HotSpot - Eclipse OpenJ9
    env: JDK=10 + Hotspot
    script: 
    - source install-jdk.sh -C --url $(curl --silent https://api.adoptopenjdk.net/openjdk10/nightly/x64_linux/ | grep 'binary_link' | grep -Eo '(http|https)://[^"]+' | head -1)
    - ./gradlew test
    - ./gradlew jacocoTestReport
  - # stage: ...
    env: JDK=10 + OpenJ9
    script: 
    - source install-jdk.sh -C --url $(curl --silent https://api.adoptopenjdk.net/openjdk10-openj9/nightly/x64_linux/ | grep 'binary_link' | grep -Eo '(http|https)://[^"]+' | head -1)
    - ./gradlew test
    - ./gradlew jacocoTestReport
  - stage: Graal & Zulu
    env: JDK=graalvm-ce-1.0.0-rc6
    script: 
    - source install-jdk.sh --url https://github.com/oracle/graal/releases/download/vm-1.0.0-rc6/graalvm-ce-1.0.0-rc6-linux-amd64.tar.gz
    - ./gradlew test
    - ./gradlew jacocoTestReport
  - # stage: ...
    env: JDK=zulu10.3+5-jdk10.0.2
    script: 
    - source install-jdk.sh --url https://cdn.azul.com/zulu/bin/zulu10.3+5-jdk10.0.2-linux_x64.tar.gz
    - ./gradlew test
    - ./gradlew jacocoTestReport
    
    
after_success:
- bash <(curl -s https://codecov.io/bash)

after_script:
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}
- ls ${JAVA_HOME}
- java -version